FROM node:current-alpine3.17
WORKDIR /app
COPY package*.json ./
RUN apk update && apk add bash
RUN npm install
RUN npm install -g @angular/cli
COPY . .
RUN npm run build
EXPOSE 4200
CMD ["npm", "start"]
